version: "3.4"

services:
  fastify:
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "9229:9229"
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - mongovol:/data/db
volumes:
  mongovol:
